# Generated by Django 4.2.1 on 2024-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='project title')),
                ('employer', models.CharField(max_length=80, verbose_name='employer')),
                ('video', models.FileField(upload_to='videos/', verbose_name='video file')),
                ('date', models.CharField(max_length=80, verbose_name='date published project')),
                ('language', models.CharField(max_length=100, verbose_name='project language')),
                ('preview', models.URLField(verbose_name='project preview')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['created'], 'verbose_name': 'Contact us', 'verbose_name_plural': 'Contact us'},
        ),
    ]
